// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get Supabase URL from environment
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Validate required environment variables with helpful error messages
if (!SUPABASE_URL) {
  console.error('Available env vars:', Object.keys(import.meta.env).filter(k => k.includes('SUPABASE')));
  throw new Error('Supabase URL not found. Please set VITE_SUPABASE_URL environment variable.');
}

if (!SUPABASE_KEY) {
  console.error('Available env vars:', Object.keys(import.meta.env).filter(k => k.includes('SUPABASE')));
  throw new Error('Supabase key not found. Please set VITE_SUPABASE_ANON_KEY environment variable.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
